# Generated by Django 5.2.1 on 2025-07-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_is_active_listing_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='views',
        ),
    ]
